name: Gyldadvancements
version: '${project.version}'
main: com.gylderia.gyldadvancements.Gyldadvancements
api-version: '1.20'
depend:
  - 'CrazyAdvancementsAPI'
softdepend:
  - 'MythicMobs'
  - 'WorldGuard'
commands:
  advancementreload: